version: '3.3'

services:

  sql-server:
    build: 
      context: ./savings-tracker/docker/db
      dockerfile: Dockerfile
    container_name: sql-server
    environment:
      - SA_PASSWORD=VerySecret1234!
    ports:
      - "1433:1433"

  savings-tracker:
    build:
      context: ./savings-tracker
      dockerfile: Dockerfile
    container_name: savings-tracker
    expose:
      - 5000
    ports:
      - 5000:5000

  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    container_name: web-ui
    ports:
      - 3000:3000