version: '3.3'

services:

  sql-server:
    build:
      context: ./savings-tracker/docker/db
      dockerfile: Dockerfile
    container_name: sql-server
    environment:
      - SA_PASSWORD=VerySecret1234!
    ports:
      - "1433:1433"

  seq:
    container_name: seq
    image: datalust/seq:2022.1
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "80:80"

  seq-udp-listener: 
    container_name: seq-udp-listener
    image: datalust/seq-input-gelf:2.0
    environment:
      - SEQ_ADDRESS=http://seq:5341
    ports:
      - "12201:12201/udp"

  localstack:
    container_name: localstack
    build:
      dockerfile: Dockerfile
      context: ./savings-tracker/docker/localstack
    environment:
      - SERVICES=ssm,kms
      - DEBUG=${DEBUG-}
      - TERRAFORM_ENVIRONMENT=local-docker
    ports:
      - "4566:4566"

  savings-tracker:
    build:
      context: ./savings-tracker
      dockerfile: Dockerfile
    container_name: savings-tracker
    environment:
      - CONFIG_FILE=config.docker
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - AWS_ACCESS_KEY_ID=eu-west-2
    expose:
      - 5000
    ports:
      - 5000:5000
    restart: on-failure

  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    container_name: web-ui
    ports:
      - 3000:3000