version: '3.3'

services:

  seq:
    container_name: seq
    image: datalust/seq:2022.1
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "80:80"

  seq-udp-listener:
    container_name: seq-udp-listener
    image: datalust/seq-input-gelf:2.0
    environment:
      - SEQ_ADDRESS=http://seq:5341
    ports:
      - "12201:12201/udp"
