version: '3.3'

services:

  sql-server:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: sql-server
    environment:
      - SA_PASSWORD=VerySecret1234!
    ports:
      - "1433:1433"

  seq:
    container_name: seq
    image: datalust/seq:2022.1
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "80:80"

  seq-udp-listener:
    container_name: seq-udp-listener
    image: datalust/seq-input-gelf:2.0
    environment:
      - SEQ_ADDRESS=http://seq:5341
    ports:
      - "12201:12201/udp"
